import 'models.dart';

const deviceBrands = ['Detectado', 'Samsung', 'Motorola', 'Xiaomi', 'iPhone'];

List<ScenarioAnswer> _answers(String safe, String help, String risky) => [
  ScenarioAnswer(AnswerType.safe, safe),
  ScenarioAnswer(AnswerType.help, help),
  ScenarioAnswer(AnswerType.risky, risky),
];

Scenario _scenario({
  required String id,
  required String sender,
  required String title,
  required String message,
  required String clue,
  required String safeAction,
  required List<ScenarioAnswer> answers,
  String link = 'Sem link',
}) => Scenario(
  id: id,
  sender: sender,
  title: title,
  message: message,
  link: link,
  clue: clue,
  safeAction: safeAction,
  answers: answers,
);

Training _training({
  required String id,
  required String name,
  required String subtitle,
  required String category,
  required String difficulty,
  required String minutes,
  required String tag,
  required List<Scenario> scenarios,
  required String feedback,
}) => Training(
  id: id,
  name: name,
  subtitle: subtitle,
  category: category,
  difficulty: difficulty,
  minutes: minutes,
  tag: tag,
  scenarios: scenarios,
  feedback: feedback,
);

final trainings = <Training>[
  _training(
    id: 'mensagem-suspeita',
    name: 'Mensagem suspeita',
    subtitle: 'Golpes por SMS ou aplicativo',
    category: 'Segurança',
    difficulty: 'Fácil',
    minutes: '5 min',
    tag: 'Recomendado',
    feedback: 'Você treinou sinais de golpe: pressa, ameaça e pedido de dados.',
    scenarios: [
      _scenario(
        id: 'msg-1',
        sender: 'SMS desconhecido',
        title: 'Conta bloqueada',
        message:
            'Seu acesso bancário foi bloqueado. Clique para resolver agora.',
        link: 'bit.ly/ajuda-banco',
        clue: 'Pressa + link encurtado',
        safeAction: 'Não clicar no link. Abra o aplicativo oficial do banco.',
        answers: _answers(
          'Abrir app oficial',
          'Perguntar antes',
          'Tocar no link',
        ),
      ),
      _scenario(
        id: 'msg-2',
        sender: 'Número estranho',
        title: 'Prêmio falso',
        message: 'Você ganhou um prêmio. Envie seus dados para receber hoje.',
        link: 'premio-agora.info',
        clue: 'Promessa boa demais',
        safeAction: 'Não enviar dados pessoais por mensagem.',
        answers: _answers(
          'Apagar mensagem',
          'Mostrar para alguém',
          'Enviar CPF',
        ),
      ),
      _scenario(
        id: 'msg-3',
        sender: 'Entrega urgente',
        title: 'Taxa de entrega',
        message:
            'Sua entrega está parada. Pague uma pequena taxa para liberar.',
        link: 'taxa-entrega.net',
        clue: 'Cobrança inesperada',
        safeAction: 'Conferir no app ou site oficial da entrega.',
        answers: _answers('Ver app da entrega', 'Pedir ajuda', 'Pagar a taxa'),
      ),
      _scenario(
        id: 'msg-4',
        sender: 'Suporte falso',
        title: 'Código de verificação',
        message:
            'Informe o código que chegou por SMS para confirmar sua conta.',
        clue: 'Pedido de código pessoal',
        safeAction: 'Nunca passe código de verificação para outra pessoa.',
        answers: _answers(
          'Guardar o código',
          'Ligar para suporte real',
          'Mandar o código',
        ),
      ),
      _scenario(
        id: 'msg-5',
        sender: 'Contato novo',
        title: 'Pedido de dinheiro',
        message: 'Oi, troquei de número. Preciso de uma transferência urgente.',
        clue: 'Urgência + número novo',
        safeAction: 'Ligue para a pessoa em um número que você já conhecia.',
        answers: _answers(
          'Ligar para a pessoa',
          'Chamar familiar',
          'Transferir agora',
        ),
      ),
      _scenario(
        id: 'msg-6',
        sender: 'Promoção',
        title: 'Cadastro suspeito',
        message: 'Atualize seus dados para não perder o benefício.',
        link: 'beneficio-seguro.online',
        clue: 'Ameaça de perder benefício',
        safeAction: 'Procure o canal oficial antes de preencher qualquer dado.',
        answers: _answers(
          'Buscar site oficial',
          'Pedir confirmação',
          'Atualizar no link',
        ),
      ),
      _scenario(
        id: 'msg-7',
        sender: 'Loja desconhecida',
        title: 'Cupom exagerado',
        message:
            'Cupom de 90% só hoje. Preencha cadastro e cartão para reservar.',
        link: 'oferta-relampago.shop',
        clue: 'Desconto alto + pedido de cartão',
        safeAction: 'Pesquise a loja fora do link recebido.',
        answers: _answers(
          'Pesquisar a loja',
          'Perguntar antes',
          'Cadastrar cartão',
        ),
      ),
      _scenario(
        id: 'msg-8',
        sender: 'Contato com áudio',
        title: 'Voz suspeita',
        message: 'Recebi um áudio curto pedindo segredo e dinheiro urgente.',
        clue: 'Pedido de segredo + urgência',
        safeAction: 'Confirme por ligação ou vídeo antes de agir.',
        answers: _answers(
          'Fazer chamada de vídeo',
          'Avisar a família',
          'Mandar dinheiro',
        ),
      ),
      _scenario(
        id: 'msg-9',
        sender: 'QR Code recebido',
        title: 'QR Code falso',
        message:
            'Escaneie este QR Code para evitar o cancelamento da sua conta.',
        link: 'Imagem com QR Code',
        clue: 'Ameaça + código desconhecido',
        safeAction: 'Não escaneie QR Code enviado por desconhecido.',
        answers: _answers(
          'Ignorar o QR Code',
          'Conferir com suporte',
          'Escanear código',
        ),
      ),
    ],
  ),
  _training(
    id: 'transferencia-instantanea',
    name: 'Transferência instantânea',
    subtitle: 'Treino sem dinheiro real',
    category: 'Banco digital',
    difficulty: 'Médio',
    minutes: '3 min',
    tag: 'Importante',
    feedback: 'Você praticou conferência de nome, valor e comprovante.',
    scenarios: [
      _scenario(
        id: 'pix-1',
        sender: 'Tela de treino',
        title: 'Chave desconhecida',
        message: 'A chave de pagamento não parece ser da pessoa combinada.',
        link: 'treino sem dinheiro real',
        clue: 'Nome diferente do combinado',
        safeAction: 'Conferir antes de confirmar. Nenhum Pix real será feito.',
        answers: _answers(
          'Revisar nome',
          'Confirmar por ligação',
          'Confirmar mesmo assim',
        ),
      ),
      _scenario(
        id: 'pix-2',
        sender: 'Tela de treino',
        title: 'Valor alterado',
        message: 'O valor ficou maior do que o combinado na conversa.',
        link: 'treino sem dinheiro real',
        clue: 'Valor divergente',
        safeAction: 'Pare e revise o valor antes de qualquer confirmação.',
        answers: _answers(
          'Corrigir valor',
          'Perguntar de novo',
          'Pagar valor maior',
        ),
      ),
      _scenario(
        id: 'pix-3',
        sender: 'Tela de treino',
        title: 'Pedido com pressa',
        message: 'A pessoa insiste para pagar agora sem conferir os dados.',
        link: 'treino sem dinheiro real',
        clue: 'Pressão para agir rápido',
        safeAction: 'Pedir ajuda ou confirmar com calma.',
        answers: _answers(
          'Parar a operação',
          'Pedir ajuda',
          'Pagar com pressa',
        ),
      ),
      _scenario(
        id: 'pix-4',
        sender: 'Tela de treino',
        title: 'Comprovante falso',
        message:
            'A pessoa mandou um comprovante por imagem e pediu devolução de valor.',
        link: 'treino sem dinheiro real',
        clue: 'Comprovante fora do app',
        safeAction:
            'Confira o saldo no aplicativo antes de devolver qualquer valor.',
        answers: _answers(
          'Ver saldo no app',
          'Chamar banco',
          'Devolver rápido',
        ),
      ),
      _scenario(
        id: 'pix-5',
        sender: 'Tela de treino',
        title: 'QR Code de cobrança',
        message: 'O QR Code mostra um recebedor diferente da loja combinada.',
        link: 'treino sem dinheiro real',
        clue: 'Recebedor diferente',
        safeAction: 'Cancelar e pedir outro meio oficial de pagamento.',
        answers: _answers(
          'Cancelar pagamento',
          'Falar com a loja',
          'Pagar o QR Code',
        ),
      ),
      _scenario(
        id: 'pix-6',
        sender: 'Tela de treino',
        title: 'Agendamento estranho',
        message:
            'O pagamento aparece agendado para outra data, mas a pessoa diz que já caiu.',
        link: 'treino sem dinheiro real',
        clue: 'Data diferente + pressão',
        safeAction: 'Conferir status no app e não enviar novo valor.',
        answers: _answers(
          'Ver status no app',
          'Pedir orientação',
          'Enviar de novo',
        ),
      ),
    ],
  ),
  _training(
    id: 'link-whatsapp',
    name: 'Link recebido no WhatsApp',
    subtitle: 'Veja quando um link merece cuidado',
    category: 'WhatsApp',
    difficulty: 'Fácil',
    minutes: '4 min',
    tag: 'Novo',
    feedback:
        'Você praticou abrir canais oficiais sem confiar no link recebido.',
    scenarios: [
      _scenario(
        id: 'wpp-link-1',
        sender: 'Grupo da família',
        title: 'Promoção de mercado',
        message: 'Mercado dando vale de R\$ 500. Abra e cadastre seu CPF.',
        link: 'vale-facil-promocao.com',
        clue: 'Promessa alta + pedido de CPF',
        safeAction: 'Não abra. Pesquise a promoção no site oficial do mercado.',
        answers: _answers(
          'Pesquisar fora do link',
          'Perguntar no grupo',
          'Cadastrar CPF',
        ),
      ),
      _scenario(
        id: 'wpp-link-2',
        sender: 'Contato desconhecido',
        title: 'Foto para baixar',
        message: 'Clique para ver as fotos que tirei de você.',
        link: 'fotos-baixar.apk',
        clue: 'Arquivo estranho para instalar',
        safeAction: 'Não baixe aplicativos enviados por mensagem.',
        answers: _answers('Apagar mensagem', 'Pedir ajuda', 'Instalar arquivo'),
      ),
    ],
  ),
  _training(
    id: 'codigo-verificacao',
    name: 'Código de verificação',
    subtitle: 'Aprenda a proteger códigos SMS',
    category: 'Segurança',
    difficulty: 'Fácil',
    minutes: '3 min',
    tag: 'Segurança',
    feedback: 'Você reforçou que código de verificação é segredo.',
    scenarios: [
      _scenario(
        id: 'code-1',
        sender: 'Pessoa no WhatsApp',
        title: 'Código emprestado',
        message: 'Mande o número que chegou por SMS para eu confirmar aqui.',
        clue: 'Pedido de código que chegou no seu celular',
        safeAction: 'Nunca passe esse código para outra pessoa.',
        answers: _answers(
          'Não enviar',
          'Perguntar a familiar',
          'Enviar o código',
        ),
      ),
      _scenario(
        id: 'code-2',
        sender: 'Ligação desconhecida',
        title: 'Atendente falso',
        message: 'Sou do suporte. Diga o código para evitar bloqueio.',
        clue: 'Ameaça + código',
        safeAction: 'Desligue e procure o suporte oficial.',
        answers: _answers(
          'Desligar',
          'Ligar no suporte oficial',
          'Ditar o código',
        ),
      ),
    ],
  ),
  _training(
    id: 'perfil-falso',
    name: 'Perfil falso pedindo dinheiro',
    subtitle: 'Confirme antes de ajudar',
    category: 'Segurança',
    difficulty: 'Fácil',
    minutes: '4 min',
    tag: 'Importante',
    feedback: 'Você treinou confirmar identidade antes de transferir.',
    scenarios: [
      _scenario(
        id: 'fake-profile-1',
        sender: 'Novo número',
        title: 'Filho pedindo Pix',
        message: 'Mãe, perdi meu celular. Faz um Pix urgente para este número.',
        clue: 'Número novo + urgência',
        safeAction: 'Ligue para o número antigo ou fale com outro familiar.',
        answers: _answers('Confirmar por ligação', 'Pedir ajuda', 'Fazer Pix'),
      ),
      _scenario(
        id: 'fake-profile-2',
        sender: 'Rede social',
        title: 'Amigo vendendo item',
        message: 'Estou vendendo barato. Pague agora para reservar.',
        clue: 'Conta pode ter sido invadida',
        safeAction: 'Confirme por outro canal antes de pagar.',
        answers: _answers(
          'Confirmar fora da rede',
          'Perguntar antes',
          'Pagar agora',
        ),
      ),
    ],
  ),
  _training(
    id: 'falso-banco',
    name: 'Golpe do falso banco',
    subtitle: 'Banco nenhum pede senha por mensagem',
    category: 'Banco digital',
    difficulty: 'Médio',
    minutes: '5 min',
    tag: 'Segurança',
    feedback: 'Você treinou reconhecer contato falso de banco.',
    scenarios: [
      _scenario(
        id: 'bank-1',
        sender: 'Atendimento Banco',
        title: 'Senha solicitada',
        message: 'Para cancelar uma compra, informe sua senha do app.',
        clue: 'Banco pedindo senha',
        safeAction: 'Banco nenhum pede senha por mensagem ou ligação.',
        answers: _answers(
          'Não informar senha',
          'Abrir app oficial',
          'Passar senha',
        ),
      ),
      _scenario(
        id: 'bank-2',
        sender: 'SMS Banco',
        title: 'Compra falsa',
        message: 'Compra aprovada. Ligue neste número para cancelar.',
        link: '0800 falso',
        clue: 'Número enviado por SMS',
        safeAction: 'Use o telefone que está no cartão ou app oficial.',
        answers: _answers('Usar canal oficial', 'Pedir ajuda', 'Ligar no SMS'),
      ),
    ],
  ),
  _training(
    id: 'suporte-tecnico-falso',
    name: 'Golpe do falso suporte técnico',
    subtitle: 'Não instale apps de acesso remoto',
    category: 'Segurança',
    difficulty: 'Médio',
    minutes: '5 min',
    tag: 'Importante',
    feedback:
        'Você identificou pedido perigoso de instalação e controle remoto.',
    scenarios: [
      _scenario(
        id: 'support-1',
        sender: 'Suporte desconhecido',
        title: 'Aplicativo para ajudar',
        message: 'Instale este app para eu mexer no seu celular e resolver.',
        link: 'controle-remoto.apk',
        clue: 'Pedido para controlar seu celular',
        safeAction: 'Não instale. Procure assistência confiável.',
        answers: _answers(
          'Recusar instalação',
          'Pedir ajuda presencial',
          'Instalar app',
        ),
      ),
      _scenario(
        id: 'support-2',
        sender: 'Ligação',
        title: 'Tela compartilhada',
        message: 'Mostre a tela enquanto abre o banco para eu conferir.',
        clue: 'Quer ver tela do banco',
        safeAction: 'Nunca compartilhe tela com banco aberto.',
        answers: _answers(
          'Fechar banco',
          'Desligar e pedir ajuda',
          'Mostrar tela',
        ),
      ),
    ],
  ),
  _training(
    id: 'comprovante-falso',
    name: 'Identificar comprovante falso',
    subtitle: 'Confira no app, não só na imagem',
    category: 'Banco digital',
    difficulty: 'Médio',
    minutes: '4 min',
    tag: 'Novo',
    feedback:
        'Você treinou verificar saldo e extrato antes de confiar em imagem.',
    scenarios: [
      _scenario(
        id: 'receipt-1',
        sender: 'Comprador',
        title: 'Imagem de comprovante',
        message: 'Já paguei. Veja a imagem e entregue o produto.',
        clue: 'Só existe imagem, não há saldo confirmado',
        safeAction: 'Confira se o valor caiu no extrato do seu banco.',
        answers: _answers(
          'Conferir extrato',
          'Pedir ajuda',
          'Entregar produto',
        ),
      ),
      _scenario(
        id: 'receipt-2',
        sender: 'Contato',
        title: 'Comprovante agendado',
        message: 'Está agendado, mas pode entregar hoje.',
        clue: 'Agendado não é dinheiro recebido',
        safeAction: 'Espere o valor cair de verdade.',
        answers: _answers(
          'Esperar cair',
          'Falar com banco',
          'Confiar na imagem',
        ),
      ),
    ],
  ),
  _training(
    id: 'saldo-extrato',
    name: 'Entender saldo e extrato',
    subtitle: 'Veja entrada, saída e cobrança',
    category: 'Banco digital',
    difficulty: 'Fácil',
    minutes: '4 min',
    tag: 'Recomendado',
    feedback: 'Você praticou procurar movimentações desconhecidas sem pânico.',
    scenarios: [
      _scenario(
        id: 'statement-1',
        sender: 'Tela de treino',
        title: 'Cobrança desconhecida',
        message: 'Apareceu uma saída que você não reconhece no extrato.',
        link: 'simulação educativa',
        clue: 'Movimento desconhecido',
        safeAction: 'Anote a data e fale com o banco pelo canal oficial.',
        answers: _answers(
          'Conferir detalhes',
          'Chamar banco oficial',
          'Ignorar sempre',
        ),
      ),
      _scenario(
        id: 'statement-2',
        sender: 'Tela de treino',
        title: 'Saldo menor',
        message: 'O saldo está menor depois de uma compra no cartão.',
        link: 'simulação educativa',
        clue: 'Pode ser compra ou tarifa',
        safeAction: 'Leia a descrição do extrato antes de agir.',
        answers: _answers(
          'Ler descrição',
          'Pedir ajuda',
          'Passar senha ao atendente',
        ),
      ),
    ],
  ),
  _training(
    id: 'boleto-sem-pagar',
    name: 'Simular boleto sem pagar',
    subtitle: 'Treino educativo sem pagamento real',
    category: 'Banco digital',
    difficulty: 'Médio',
    minutes: '5 min',
    tag: 'Segurança',
    feedback: 'Você praticou conferir beneficiário, valor e vencimento.',
    scenarios: [
      _scenario(
        id: 'boleto-1',
        sender: 'Tela de treino',
        title: 'Beneficiário estranho',
        message: 'O boleto da loja mostra outro nome como recebedor.',
        link: 'simulação educativa',
        clue: 'Beneficiário diferente',
        safeAction: 'Não avance. Confirme com a loja por canal oficial.',
        answers: _answers(
          'Conferir beneficiário',
          'Falar com loja',
          'Pagar mesmo assim',
        ),
      ),
      _scenario(
        id: 'boleto-2',
        sender: 'E-mail',
        title: 'Boleto urgente',
        message: 'Pague hoje para evitar processo. Abra o anexo.',
        link: 'boleto-anexo.pdf',
        clue: 'Ameaça + anexo inesperado',
        safeAction: 'Não abra anexos inesperados. Procure a empresa oficial.',
        answers: _answers('Não abrir anexo', 'Pedir ajuda', 'Pagar por medo'),
      ),
    ],
  ),
  _training(
    id: 'tela-falsa-banco',
    name: 'Reconhecer tela falsa de banco',
    subtitle: 'Compare com o app oficial',
    category: 'Banco digital',
    difficulty: 'Médio',
    minutes: '4 min',
    tag: 'Importante',
    feedback: 'Você treinou desconfiar de telas copiadas e links externos.',
    scenarios: [
      _scenario(
        id: 'fake-bank-screen-1',
        sender: 'Página aberta pelo link',
        title: 'Login parecido',
        message: 'A tela parece do banco, mas abriu no navegador por um link.',
        link: 'banco-seguro-login.net',
        clue: 'Banco aberto fora do app oficial',
        safeAction: 'Feche a página e abra o app oficial instalado.',
        answers: _answers('Fechar e abrir app', 'Pedir ajuda', 'Digitar senha'),
      ),
      _scenario(
        id: 'fake-bank-screen-2',
        sender: 'Página de atualização',
        title: 'Atualizar cadastro',
        message: 'A página pede senha, CPF e foto do documento.',
        link: 'atualiza-conta.info',
        clue: 'Pede dados demais',
        safeAction: 'Não preencha dados pessoais em links recebidos.',
        answers: _answers(
          'Não preencher',
          'Ligar no banco',
          'Mandar documento',
        ),
      ),
    ],
  ),
  _training(
    id: 'conectar-wifi',
    name: 'Conectar no Wi-Fi',
    subtitle: 'Pratique encontrar a rede correta',
    category: 'Celular',
    difficulty: 'Fácil',
    minutes: '3 min',
    tag: 'Novo',
    feedback: 'Você praticou escolher rede conhecida e evitar Wi-Fi suspeito.',
    scenarios: [
      _scenario(
        id: 'wifi-train-1',
        sender: 'Tela do celular',
        title: 'Rede desconhecida',
        message: 'Apareceu Wi-Fi grátis com nome estranho perto de você.',
        clue: 'Rede pública desconhecida',
        safeAction: 'Para banco, prefira dados móveis ou Wi-Fi de casa.',
        answers: _answers(
          'Usar rede conhecida',
          'Pedir ajuda',
          'Entrar no Wi-Fi grátis',
        ),
      ),
      _scenario(
        id: 'wifi-train-2',
        sender: 'Tela do celular',
        title: 'Senha do Wi-Fi',
        message: 'A rede de casa pede senha para conectar.',
        clue: 'Rede conhecida',
        safeAction: 'Digite somente a senha da sua rede de confiança.',
        answers: _answers(
          'Usar senha de casa',
          'Pedir ao responsável',
          'Usar qualquer rede',
        ),
      ),
    ],
  ),
  _training(
    id: 'app-travado',
    name: 'Fechar aplicativo travado',
    subtitle: 'Saia sem apagar dados',
    category: 'Celular',
    difficulty: 'Fácil',
    minutes: '3 min',
    tag: 'Novo',
    feedback:
        'Você treinou fechar e abrir novamente sem mexer em configurações sensíveis.',
    scenarios: [
      _scenario(
        id: 'frozen-app-1',
        sender: 'Tela do celular',
        title: 'App não responde',
        message: 'O aplicativo parou e nenhum botão funciona.',
        clue: 'App travado',
        safeAction: 'Abra apps recentes, feche o app e tente novamente.',
        answers: _answers(
          'Fechar app recente',
          'Pedir ajuda',
          'Apagar qualquer coisa',
        ),
      ),
      _scenario(
        id: 'frozen-app-2',
        sender: 'Tela do celular',
        title: 'Banco travou',
        message: 'O app do banco travou durante uma simulação.',
        clue: 'Não concluir ações com tela travada',
        safeAction: 'Feche o app. Se tiver dúvida, fale com o banco oficial.',
        answers: _answers(
          'Fechar aplicativo',
          'Ligar no banco',
          'Tocar várias vezes',
        ),
      ),
    ],
  ),
  _training(
    id: 'atualizar-aplicativo',
    name: 'Atualizar aplicativo',
    subtitle: 'Use a loja oficial do celular',
    category: 'Celular',
    difficulty: 'Fácil',
    minutes: '4 min',
    tag: 'Recomendado',
    feedback: 'Você praticou atualizar pela Play Store ou App Store.',
    scenarios: [
      _scenario(
        id: 'update-app-1',
        sender: 'Mensagem',
        title: 'Atualização por link',
        message: 'Atualize seu banco por este link antes de ser bloqueado.',
        link: 'novo-banco.apk',
        clue: 'Atualização fora da loja oficial',
        safeAction: 'Atualize aplicativos apenas pela loja oficial.',
        answers: _answers('Abrir loja oficial', 'Pedir ajuda', 'Instalar link'),
      ),
      _scenario(
        id: 'update-app-2',
        sender: 'Play Store',
        title: 'Botão atualizar',
        message: 'A loja oficial mostra o botão Atualizar.',
        link: 'loja oficial',
        clue: 'Canal confiável',
        safeAction: 'Pode atualizar pela loja oficial.',
        answers: _answers('Atualizar na loja', 'Pedir ajuda', 'Enviar senha'),
      ),
    ],
  ),
  _training(
    id: 'bloquear-denunciar-whatsapp',
    name: 'Bloquear e denunciar no WhatsApp',
    subtitle: 'Reduza mensagens perigosas',
    category: 'WhatsApp',
    difficulty: 'Fácil',
    minutes: '4 min',
    tag: 'Novo',
    feedback: 'Você treinou bloquear, denunciar e não responder golpes.',
    scenarios: [
      _scenario(
        id: 'block-wpp-1',
        sender: 'Número desconhecido',
        title: 'Mensagem insistente',
        message: 'A pessoa manda links e pede dinheiro várias vezes.',
        clue: 'Contato insistente e suspeito',
        safeAction: 'Bloqueie, denuncie e não responda.',
        answers: _answers(
          'Bloquear contato',
          'Pedir ajuda',
          'Continuar conversa',
        ),
      ),
      _scenario(
        id: 'block-wpp-2',
        sender: 'Grupo',
        title: 'Mensagem falsa',
        message: 'Alguém enviou golpe no grupo da família.',
        clue: 'Pode enganar outras pessoas',
        safeAction: 'Avise com calma que pode ser golpe e não clique.',
        answers: _answers(
          'Avisar o grupo',
          'Pedir confirmação',
          'Repassar mensagem',
        ),
      ),
    ],
  ),
  _training(
    id: 'numero-desconhecido',
    name: 'Verificar número desconhecido',
    subtitle: 'Confirme antes de conversar',
    category: 'WhatsApp',
    difficulty: 'Fácil',
    minutes: '3 min',
    tag: 'Segurança',
    feedback: 'Você treinou confirmar identidade antes de confiar.',
    scenarios: [
      _scenario(
        id: 'unknown-number-1',
        sender: 'Número novo',
        title: 'Sou seu neto',
        message: 'Salva meu número novo e me ajuda com um pagamento.',
        clue: 'Identidade sem confirmação',
        safeAction: 'Confirme com a pessoa por outro canal.',
        answers: _answers('Confirmar antes', 'Chamar familiar', 'Pagar agora'),
      ),
      _scenario(
        id: 'unknown-number-2',
        sender: 'Contato sem foto',
        title: 'Pedido de segredo',
        message: 'Não conta para ninguém, preciso de dinheiro hoje.',
        clue: 'Segredo + urgência',
        safeAction: 'Não mantenha segredo. Peça ajuda.',
        answers: _answers(
          'Falar com alguém',
          'Ligar para familiar',
          'Enviar Pix',
        ),
      ),
    ],
  ),
];

DictionaryTerm _term(
  String key,
  String title,
  String category,
  String description,
  String example,
  String alert,
  String tip, {
  List<String> related = const [],
  List<String> tags = const [],
}) => DictionaryTerm(
  key: key,
  title: title,
  category: category,
  description: description,
  example: example,
  alert: alert,
  tip: tip,
  related: related,
  tags: tags,
);

final dictionaryTerms = <DictionaryTerm>[
  _term(
    'link',
    'Link',
    'Segurança',
    'Um caminho que abre uma página, foto, vídeo ou aplicativo.',
    'Geralmente aparece azul, sublinhado ou dentro de um botão.',
    'Cuidado com links enviados por desconhecidos.',
    'Na dúvida, feche a tela e procure o site oficial.',
    related: ['Phishing', 'Link suspeito'],
    tags: ['internet', 'golpe'],
  ),
  _term(
    'golpe',
    'Golpe',
    'Segurança',
    'Uma tentativa de enganar alguém para roubar dados ou dinheiro.',
    'Pode aparecer como mensagem urgente, prêmio ou falsa cobrança.',
    'Desconfie de pressa, ameaça e pedido de senha.',
    'Pare, respire e peça ajuda antes de agir.',
    tags: ['segurança'],
  ),
  _term(
    'phishing',
    'Phishing',
    'Segurança',
    'Golpe que usa mensagem falsa para pegar senha, código ou dados.',
    'Uma mensagem imita banco, loja ou entrega.',
    'Banco nenhum pede senha por mensagem.',
    'Abra o app oficial em vez de tocar no link.',
    related: ['Golpe', 'Link suspeito'],
    tags: ['segurança'],
  ),
  _term(
    'link-suspeito',
    'Link suspeito',
    'Segurança',
    'Link que parece estranho, encurtado ou enviado com pressa.',
    'bit.ly, premio-agora.info ou nome parecido com banco.',
    'Não toque se você não tem certeza.',
    'Pesquise o nome da empresa fora do link.',
    tags: ['segurança', 'internet'],
  ),
  _term(
    'senha',
    'Senha',
    'Segurança',
    'Uma chave pessoal usada para entrar em contas e aplicativos.',
    'Ela deve ser guardada como segredo.',
    'Nunca envie senha por mensagem.',
    'Use senha diferente para banco, e-mail e redes sociais.',
    tags: ['segurança'],
  ),
  _term(
    'codigo',
    'Código de verificação',
    'Segurança',
    'Números enviados para confirmar que é você usando a conta.',
    'Pode chegar por SMS ou aplicativo.',
    'Nunca passe esse código para outra pessoa.',
    'Se alguém pedir o código, pare e peça ajuda.',
    related: ['SMS', 'Autenticação em duas etapas'],
    tags: ['segurança'],
  ),
  _term(
    'duas-etapas',
    'Autenticação em duas etapas',
    'Segurança',
    'Proteção extra além da senha.',
    'Depois da senha, o app pede um código ou confirmação.',
    'Não aprove entrada que você não pediu.',
    'Ative essa proteção em banco, e-mail e WhatsApp.',
    tags: ['segurança'],
  ),
  _term(
    'sms',
    'SMS',
    'Celular e internet',
    'Mensagem de texto que chega pelo chip do celular.',
    'Bancos e serviços podem mandar avisos por SMS.',
    'Não responda SMS pedindo senha ou código.',
    'Leia com calma e confira o remetente.',
    tags: ['celular'],
  ),
  _term(
    'whatsapp',
    'WhatsApp',
    'Celular e internet',
    'Aplicativo de mensagens usado para conversar.',
    'Você recebe texto, áudio, foto e chamada.',
    'Desconfie de pedido de dinheiro por número novo.',
    'Confirme por ligação antes de transferir.',
    tags: ['whatsapp'],
  ),
  _term(
    'conta-invadida',
    'Conta invadida',
    'Segurança',
    'Quando outra pessoa consegue entrar na sua conta sem permissão.',
    'Um perfil começa a mandar mensagens que você não escreveu.',
    'Troque a senha e avise contatos.',
    'Use recuperação oficial do aplicativo.',
    tags: ['segurança'],
  ),
  _term(
    'clonagem',
    'Clonagem',
    'Segurança',
    'Quando alguém tenta copiar sua conta ou se passar por você.',
    'A pessoa usa sua foto e pede dinheiro aos seus contatos.',
    'Avise familiares e bloqueie o perfil falso.',
    'Ative verificação em duas etapas.',
    tags: ['segurança'],
  ),
  _term(
    'perfil-falso',
    'Perfil falso',
    'Segurança',
    'Conta criada para parecer outra pessoa ou empresa.',
    'Usa foto conhecida, mas número ou nome estranho.',
    'Não envie dinheiro sem confirmar.',
    'Ligue para a pessoa real antes de responder.',
    tags: ['segurança'],
  ),
  _term(
    'malware',
    'Malware',
    'Segurança',
    'Programa ruim que pode roubar dados ou atrapalhar o celular.',
    'Pode vir em aplicativo falso ou arquivo recebido.',
    'Não instale arquivo enviado por mensagem.',
    'Baixe apps só pela loja oficial.',
    tags: ['segurança', 'app'],
  ),
  _term(
    'virus',
    'Vírus',
    'Segurança',
    'Tipo de programa ruim que prejudica aparelho ou dados.',
    'Pode aparecer após baixar arquivo estranho.',
    'Evite clicar em alertas assustadores.',
    'Mantenha o celular atualizado.',
    tags: ['segurança'],
  ),
  _term(
    'app-falso',
    'Aplicativo falso',
    'Segurança',
    'Aplicativo que finge ser banco, loja ou serviço conhecido.',
    'Pode usar nome e imagem parecidos com o app verdadeiro.',
    'Não baixe app enviado por link.',
    'Confira desenvolvedor, avaliações e loja oficial.',
    tags: ['app', 'segurança'],
  ),
  _term(
    'permissao-app',
    'Permissão do aplicativo',
    'Celular e internet',
    'Autorização para o app usar câmera, localização, contatos ou fotos.',
    'Um app de lanterna pedindo acesso ao banco é estranho.',
    'Não aceite permissões que não fazem sentido.',
    'Revise permissões nas configurações.',
    tags: ['app'],
  ),
  _term(
    'dados-pessoais',
    'Dados pessoais',
    'Segurança',
    'Informações que identificam você.',
    'Nome, telefone, endereço, CPF e foto de documento.',
    'Não envie dados por link recebido.',
    'Compartilhe só quando tiver certeza do canal oficial.',
    tags: ['privacidade'],
  ),
  _term(
    'cpf',
    'CPF',
    'Segurança',
    'Número de documento usado para identificar uma pessoa.',
    'Pode ser pedido em cadastro oficial.',
    'Não mande CPF em promoção recebida por mensagem.',
    'Na dúvida, peça ajuda antes de informar.',
    tags: ['privacidade'],
  ),
  _term(
    'foto-documento',
    'Foto de documento',
    'Segurança',
    'Imagem do RG, CNH ou outro documento.',
    'Pode ser usada para cadastro e validação.',
    'Nunca envie foto de documento por WhatsApp desconhecido.',
    'Use apenas apps oficiais e confiáveis.',
    tags: ['privacidade'],
  ),
  _term(
    'chave-pix',
    'Chave Pix',
    'Banco digital',
    'Informação usada para receber Pix.',
    'Pode ser CPF, telefone, e-mail ou chave aleatória.',
    'Confira o nome antes de transferir.',
    'Prefira chave aleatória quando possível.',
    tags: ['pix'],
  ),
  _term(
    'qr-code',
    'QR Code',
    'Banco digital',
    'Código quadrado que o celular lê pela câmera.',
    'Pode abrir site ou pagamento.',
    'Não escaneie QR Code enviado por desconhecido.',
    'Confira valor e recebedor antes de confirmar.',
    tags: ['pagamento'],
  ),
  _term(
    'boleto-falso',
    'Boleto falso',
    'Banco digital',
    'Boleto alterado para o dinheiro cair para golpista.',
    'O nome do beneficiário pode estar diferente.',
    'Confira beneficiário, valor e banco antes de pagar.',
    'Se veio por mensagem estranha, fale com a empresa oficial.',
    tags: ['pagamento'],
  ),
  _term(
    'wifi',
    'Wi-Fi',
    'Celular e internet',
    'Internet sem fio usada em casa ou lugares públicos.',
    'O símbolo costuma aparecer no topo da tela.',
    'Evite redes desconhecidas para acessar banco.',
    'Use Wi-Fi de confiança ou dados móveis.',
    tags: ['internet'],
  ),
  _term(
    'dados-moveis',
    'Dados móveis',
    'Celular e internet',
    'Internet que usa o chip da operadora.',
    'Funciona fora de casa quando há sinal.',
    'Pode gastar seu pacote de internet.',
    'Para banco fora de casa, pode ser mais seguro que Wi-Fi público.',
    tags: ['internet'],
  ),
  _term(
    'bluetooth',
    'Bluetooth',
    'Celular e internet',
    'Conexão curta entre aparelhos próximos.',
    'Serve para fone, caixa de som ou relógio.',
    'Desative se aparecer pareamento desconhecido.',
    'Aceite conexão só de aparelho que você reconhece.',
    tags: ['celular'],
  ),
  _term(
    'modo-aviao',
    'Modo avião',
    'Celular e internet',
    'Modo que desliga sinal, dados móveis e algumas conexões.',
    'Pode ser ativado sem querer nos atalhos.',
    'Se estiver ligado, chamadas e internet podem parar.',
    'Desative nos atalhos rápidos quando precisar de sinal.',
    tags: ['celular'],
  ),
  _term(
    'atualizacao',
    'Atualização',
    'Celular e internet',
    'Melhoria do sistema ou aplicativo.',
    'A loja oficial mostra botão Atualizar.',
    'Não atualize banco por link recebido.',
    'Atualize pela Play Store ou App Store.',
    tags: ['app'],
  ),
  _term(
    'backup',
    'Backup',
    'Celular e internet',
    'Cópia de segurança de fotos, conversas ou arquivos.',
    'Ajuda a recuperar se trocar de celular.',
    'Não dê sua senha para alguém fazer backup.',
    'Use conta oficial e peça ajuda de confiança.',
    tags: ['celular'],
  ),
  _term(
    'nuvem',
    'Nuvem',
    'Celular e internet',
    'Lugar online onde arquivos podem ficar guardados.',
    'Google Drive, iCloud e fotos online.',
    'Proteja a conta da nuvem com senha forte.',
    'Não compartilhe pasta com desconhecidos.',
    tags: ['internet'],
  ),
  _term(
    'aplicativo',
    'Aplicativo',
    'Celular e internet',
    'Programa instalado no celular.',
    'Banco, WhatsApp, câmera e mapas são aplicativos.',
    'Baixe apenas de loja oficial.',
    'Apague apps que você não usa ou não reconhece.',
    tags: ['app'],
  ),
  _term(
    'play-store',
    'Play Store',
    'Celular e internet',
    'Loja oficial de aplicativos do Android.',
    'Usada em Samsung, Motorola e Xiaomi.',
    'Evite instalar apps fora da loja.',
    'Confira nome do desenvolvedor.',
    tags: ['app'],
  ),
  _term(
    'app-store',
    'App Store',
    'Celular e internet',
    'Loja oficial de aplicativos do iPhone.',
    'É por ela que você baixa apps no iPhone.',
    'Não instale perfis estranhos para baixar app.',
    'Use busca dentro da loja oficial.',
    tags: ['app'],
  ),
  _term(
    'download',
    'Download',
    'Celular e internet',
    'Baixar algo da internet para o celular.',
    'Pode ser foto, PDF ou aplicativo.',
    'Não baixe arquivo enviado por desconhecido.',
    'Se for app, use a loja oficial.',
    tags: ['internet'],
  ),
  _term(
    'navegador',
    'Navegador',
    'Celular e internet',
    'Aplicativo para abrir sites.',
    'Chrome, Safari e Edge são navegadores.',
    'Banco aberto por link no navegador pode ser falso.',
    'Para banco, prefira o app oficial.',
    tags: ['internet'],
  ),
  _term(
    'aba',
    'Aba',
    'Celular e internet',
    'Uma página aberta dentro do navegador.',
    'Você pode ter várias abas abertas ao mesmo tempo.',
    'Feche abas estranhas que pedem dados.',
    'Use o botão de abas para organizar.',
    tags: ['internet'],
  ),
  _term(
    'notificacao',
    'Notificação',
    'Celular e internet',
    'Aviso que aparece na tela do celular.',
    'Mensagem nova, atualização ou alerta.',
    'Não toque em aviso suspeito de prêmio ou bloqueio.',
    'Abra o app oficial se tiver dúvida.',
    tags: ['celular'],
  ),
  _term(
    'configuracoes',
    'Configurações',
    'Celular e internet',
    'Área onde você ajusta o celular.',
    'Wi-Fi, som, brilho e aplicativos ficam lá.',
    'Não mude opções que não entende sem ajuda.',
    'Procure pelo nome da função na busca das configurações.',
    tags: ['celular'],
  ),
  _term(
    'tela-inicial',
    'Tela inicial',
    'Celular e internet',
    'Primeira tela onde ficam aplicativos e atalhos.',
    'É onde você toca nos ícones.',
    'Cuidado com ícones de apps falsos parecidos.',
    'Organize apps importantes em local fácil.',
    tags: ['celular'],
  ),
  _term(
    'icone',
    'Ícone',
    'Celular e internet',
    'Desenho pequeno que representa um aplicativo ou função.',
    'O telefone pode ter ícone verde de ligação.',
    'Golpistas podem copiar ícones famosos.',
    'Leia o nome do app antes de abrir.',
    tags: ['celular'],
  ),
  _term(
    'volume',
    'Volume',
    'Celular e internet',
    'Controle que aumenta ou diminui o som.',
    'Botões laterais mudam o volume.',
    'Se não ouvir ligação, pode estar no silencioso.',
    'Teste mídia, toque e chamada separadamente.',
    tags: ['celular'],
  ),
  _term(
    'brilho',
    'Brilho',
    'Celular e internet',
    'Claridade da tela.',
    'Pode ser ajustado nos atalhos rápidos.',
    'Tela escura demais dificulta leitura.',
    'Aumente o brilho e confira modo economia.',
    tags: ['celular'],
  ),
  _term(
    'localizacao',
    'Localização',
    'Celular e internet',
    'Permissão para o app saber onde você está.',
    'Mapas precisam; lanterna normalmente não precisa.',
    'Não aceite localização para app estranho.',
    'Desative quando não for necessário.',
    tags: ['privacidade'],
  ),
  _term(
    'pix',
    'Pix',
    'Banco digital',
    'Forma de transferir dinheiro rapidamente pelo banco.',
    'Você confere nome e valor antes de confirmar.',
    'Pix geralmente não cancela depois de confirmado.',
    'Revise tudo com calma antes de apertar confirmar.',
    tags: ['pix'],
  ),
  _term(
    'transferencia',
    'Transferência',
    'Banco digital',
    'Envio de dinheiro de uma conta para outra.',
    'Pode ser Pix, TED ou outro tipo.',
    'Não transfira por pressão ou ameaça.',
    'Confirme pessoa, banco e valor.',
    tags: ['banco'],
  ),
  _term(
    'comprovante',
    'Comprovante',
    'Banco digital',
    'Registro de uma operação feita.',
    'Pode mostrar data, valor e recebedor.',
    'Imagem de comprovante pode ser falsa.',
    'Confira o extrato para ver se o dinheiro caiu.',
    tags: ['banco'],
  ),
  _term(
    'saldo',
    'Saldo',
    'Banco digital',
    'Valor disponível na conta.',
    'Mostra quanto dinheiro há no momento.',
    'Não mostre saldo em chamada de vídeo.',
    'Confira pelo app oficial.',
    tags: ['banco'],
  ),
  _term(
    'extrato',
    'Extrato',
    'Banco digital',
    'Lista de entradas e saídas da conta.',
    'Mostra compras, Pix e tarifas.',
    'Se houver cobrança desconhecida, fale com o banco oficial.',
    'Anote data e valor antes de pedir ajuda.',
    tags: ['banco'],
  ),
  _term(
    'agencia',
    'Agência',
    'Banco digital',
    'Número da unidade do banco ligada à conta.',
    'Às vezes aparece junto da conta.',
    'Não é senha, mas evite publicar em redes sociais.',
    'Informe apenas em canais confiáveis.',
    tags: ['banco'],
  ),
  _term(
    'conta',
    'Conta',
    'Banco digital',
    'Registro que guarda seu dinheiro no banco.',
    'Tem número, agência e titular.',
    'Ninguém precisa da sua senha para depositar.',
    'Use o app oficial para consultar.',
    tags: ['banco'],
  ),
  _term(
    'cartao-virtual',
    'Cartão virtual',
    'Banco digital',
    'Cartão criado no app para compras online.',
    'Pode ter número diferente do cartão físico.',
    'Use apenas em lojas confiáveis.',
    'Apague ou bloqueie se suspeitar de uso indevido.',
    tags: ['cartão'],
  ),
  _term(
    'limite',
    'Limite',
    'Banco digital',
    'Valor máximo que pode ser usado no cartão ou crédito.',
    'Não é dinheiro extra; é dívida se usar.',
    'Desconfie de promessa de aumentar limite por taxa.',
    'Aumente limite só no app oficial.',
    tags: ['banco'],
  ),
  _term(
    'emprestimo',
    'Empréstimo',
    'Banco digital',
    'Dinheiro que o banco empresta e deve ser pago depois.',
    'Normalmente tem juros.',
    'Não aceite empréstimo por pressão de mensagem.',
    'Leia valores e parcelas com ajuda.',
    tags: ['banco'],
  ),
  _term(
    'tarifa',
    'Tarifa',
    'Banco digital',
    'Valor cobrado por algum serviço.',
    'Pode aparecer no extrato.',
    'Cobrança desconhecida deve ser conferida.',
    'Fale com o banco pelo canal oficial.',
    tags: ['banco'],
  ),
  _term(
    'beneficiario',
    'Beneficiário',
    'Banco digital',
    'Pessoa ou empresa que recebe um pagamento.',
    'No boleto, é o nome de quem receberá o dinheiro.',
    'Se o nome estiver diferente, não pague.',
    'Confira antes de confirmar.',
    tags: ['pagamento'],
  ),
  _term(
    'favorecido',
    'Favorecido',
    'Banco digital',
    'Pessoa ou conta escolhida para receber dinheiro.',
    'Aparece antes de finalizar transferência.',
    'Confira nome completo antes de transferir.',
    'Se estiver diferente, cancele.',
    tags: ['pagamento'],
  ),
];

DeviceHelp _help(
  String key,
  String title,
  String category,
  List<String> android,
  List<String> iphone,
  String visual,
  String whenToAskHelp, {
  String alert = '',
}) => DeviceHelp(
  key: key,
  title: title,
  category: category,
  visual: visual,
  whenToAskHelp: whenToAskHelp,
  alert: alert,
  steps: {
    'Samsung': android,
    'Motorola': android,
    'Xiaomi': android,
    'iPhone': iphone,
    'Detectado': android,
  },
);

final deviceHelpItems = <DeviceHelp>[
  _help(
    'internet',
    'Internet não funciona',
    'Internet e Wi-Fi',
    [
      'Abra os atalhos rápidos.',
      'Confira se Wi-Fi ou dados móveis estão ligados.',
      'Tente abrir um site simples.',
    ],
    [
      'Abra a Central de Controle.',
      'Confira Wi-Fi ou dados celulares.',
      'Tente abrir um site simples.',
    ],
    'Ícone de Wi-Fi ou dados móveis no topo da tela.',
    'Peça ajuda se nenhum site abrir depois de reiniciar.',
    alert: 'Evite acessar banco em Wi-Fi público desconhecido.',
  ),
  _help(
    'sound',
    'Celular sem som',
    'Som e tela',
    [
      'Aperte volume para cima.',
      'Confira se está no silencioso.',
      'Teste um vídeo curto.',
    ],
    ['Confira a chave lateral.', 'Aumente o volume.', 'Teste um vídeo curto.'],
    'Controle de volume com a barra subindo.',
    'Peça ajuda se o alto-falante não tocar nada.',
    alert: 'Não aceite ligação de suporte pedindo senha.',
  ),
  _help(
    'brightness',
    'Tela muito escura',
    'Som e tela',
    [
      'Abra os atalhos rápidos.',
      'Aumente a barra de brilho.',
      'Confira modo economia.',
    ],
    [
      'Abra a Central de Controle.',
      'Arraste o brilho para cima.',
      'Confira modo baixo consumo.',
    ],
    'Barra de brilho no centro da tela.',
    'Peça ajuda se a tela continuar quase apagada.',
  ),
  _help(
    'app',
    'Aplicativo travou',
    'Aplicativos',
    ['Abra apps recentes.', 'Feche o app travado.', 'Abra novamente.'],
    ['Abra a troca de apps.', 'Deslize o app para cima.', 'Abra novamente.'],
    'Lista de apps recentes com um app sendo fechado.',
    'Peça ajuda se o app sempre travar.',
    alert: 'Se for app de banco, não tente várias vezes com pressa.',
  ),
  _help(
    'wifi-connect',
    'Wi-Fi não conecta',
    'Internet e Wi-Fi',
    [
      'Abra Configurações.',
      'Toque em Wi-Fi.',
      'Escolha sua rede e digite a senha.',
    ],
    ['Abra Ajustes.', 'Toque em Wi-Fi.', 'Escolha a rede e digite a senha.'],
    'Nome da rede com cadeado e sinal.',
    'Peça ajuda se a senha estiver correta e não conectar.',
    alert: 'Não use rede desconhecida para banco.',
  ),
  _help(
    'slow-phone',
    'Celular lento',
    'Desempenho',
    [
      'Feche apps abertos.',
      'Reinicie o celular.',
      'Apague arquivos que não usa.',
    ],
    ['Feche apps abertos.', 'Reinicie o iPhone.', 'Confira armazenamento.'],
    'Tela de apps recentes com poucos apps abertos.',
    'Peça ajuda se continuar muito lento.',
  ),
  _help(
    'forgot-password',
    'Esqueci a senha do celular',
    'Acesso',
    [
      'Procure a opção Esqueci senha se aparecer.',
      'Use a conta Google cadastrada.',
      'Peça ajuda presencial de confiança.',
    ],
    [
      'Use recuperação pelo ID Apple.',
      'Siga as instruções oficiais.',
      'Peça ajuda presencial de confiança.',
    ],
    'Tela de bloqueio com opção de recuperação.',
    'Procure assistência oficial se não conseguir entrar.',
    alert: 'Não passe senha antiga ou código para desconhecidos.',
  ),
  _help(
    'download-app',
    'Não consigo baixar aplicativo',
    'Aplicativos',
    [
      'Abra a Play Store.',
      'Confira internet e espaço livre.',
      'Tente baixar novamente.',
    ],
    [
      'Abra a App Store.',
      'Confira internet e espaço livre.',
      'Tente baixar novamente.',
    ],
    'Loja oficial aberta no app desejado.',
    'Peça ajuda se aparecer cobrança ou senha que você não reconhece.',
    alert: 'Não baixe app por link enviado em mensagem.',
  ),
  _help(
    'update-app',
    'Não consigo atualizar aplicativo',
    'Aplicativos',
    ['Abra a Play Store.', 'Procure o app.', 'Toque em Atualizar.'],
    ['Abra a App Store.', 'Toque no seu perfil.', 'Atualize o app.'],
    'Botão Atualizar dentro da loja oficial.',
    'Peça ajuda se a loja pedir dados estranhos.',
    alert: 'Atualização de banco deve ser pela loja oficial.',
  ),
  _help(
    'storage-full',
    'Memória cheia',
    'Armazenamento',
    [
      'Abra Configurações.',
      'Procure Armazenamento.',
      'Apague downloads e fotos repetidas.',
    ],
    [
      'Abra Ajustes.',
      'Toque em Geral e Armazenamento.',
      'Apague apps ou fotos sem uso.',
    ],
    'Barra de armazenamento quase cheia.',
    'Peça ajuda antes de apagar fotos importantes.',
  ),
  _help(
    'no-sms',
    'Não recebo SMS',
    'Mensagens',
    [
      'Confira sinal da operadora.',
      'Desative modo avião.',
      'Reinicie o celular.',
    ],
    [
      'Confira sinal da operadora.',
      'Desative modo avião.',
      'Reinicie o iPhone.',
    ],
    'Barras de sinal no topo da tela.',
    'Peça ajuda se nenhum SMS chegar por muito tempo.',
    alert: 'Nunca compartilhe código SMS quando ele chegar.',
  ),
  _help(
    'no-code',
    'Não recebo código de verificação',
    'Segurança',
    [
      'Confira SMS e internet.',
      'Espere alguns minutos.',
      'Peça reenviar uma vez.',
    ],
    [
      'Confira SMS e internet.',
      'Espere alguns minutos.',
      'Peça reenviar uma vez.',
    ],
    'Campo de código aguardando números.',
    'Peça ajuda se o código não chegar após tentativas.',
    alert: 'Nunca passe esse código para outra pessoa.',
  ),
  _help(
    'whatsapp-open',
    'WhatsApp não abre',
    'WhatsApp',
    ['Feche e abra de novo.', 'Confira internet.', 'Atualize pela Play Store.'],
    ['Feche e abra de novo.', 'Confira internet.', 'Atualize pela App Store.'],
    'Ícone do WhatsApp na tela inicial.',
    'Peça ajuda se pedir código inesperado.',
    alert: 'Se pedirem código, não envie.',
  ),
  _help(
    'send-photo',
    'Não consigo enviar foto',
    'WhatsApp',
    [
      'Confira internet.',
      'Veja se o WhatsApp pode acessar fotos.',
      'Tente enviar uma foto menor.',
    ],
    [
      'Confira internet.',
      'Permita acesso a Fotos.',
      'Tente enviar uma foto menor.',
    ],
    'Botão de clipe ou câmera na conversa.',
    'Peça ajuda se nenhuma foto enviar.',
  ),
  _help(
    'camera',
    'Câmera não funciona',
    'Câmera e microfone',
    [
      'Feche o app da câmera.',
      'Confira permissão da câmera.',
      'Reinicie o celular.',
    ],
    ['Feche a câmera.', 'Confira permissão em Ajustes.', 'Reinicie o iPhone.'],
    'Tela da câmera com permissão ativada.',
    'Peça ajuda se a tela ficar preta.',
  ),
  _help(
    'microphone',
    'Microfone não funciona',
    'Câmera e microfone',
    [
      'Confira permissão do microfone.',
      'Aumente volume de chamada.',
      'Teste gravador de voz.',
    ],
    [
      'Confira permissão do microfone.',
      'Teste gravação de voz.',
      'Reinicie o iPhone.',
    ],
    'Permissão de microfone ativada.',
    'Peça ajuda se ninguém ouvir sua voz.',
  ),
  _help(
    'battery',
    'Bateria acabando rápido',
    'Bateria',
    ['Diminua brilho.', 'Feche apps sem uso.', 'Ative economia de bateria.'],
    ['Diminua brilho.', 'Feche apps sem uso.', 'Ative modo pouca energia.'],
    'Ícone de bateria com modo economia.',
    'Peça ajuda se a bateria estufar ou descarregar muito rápido.',
  ),
  _help(
    'hot-phone',
    'Celular esquentando',
    'Bateria',
    [
      'Tire da tomada.',
      'Feche jogos ou vídeos.',
      'Deixe descansar em local fresco.',
    ],
    [
      'Tire da tomada.',
      'Feche apps pesados.',
      'Deixe descansar em local fresco.',
    ],
    'Celular fora do carregador e sem capa pesada.',
    'Procure assistência se esquentar sempre.',
    alert: 'Não coloque na geladeira ou água.',
  ),
  _help(
    'notification',
    'Notificação não aparece',
    'Notificações',
    [
      'Abra Configurações.',
      'Procure Notificações.',
      'Ative para o app desejado.',
    ],
    ['Abra Ajustes.', 'Toque em Notificações.', 'Ative para o app desejado.'],
    'Tela de notificações com botão ativado.',
    'Peça ajuda se o app importante continuar sem avisar.',
  ),
  _help(
    'keyboard',
    'Teclado sumiu',
    'Teclado',
    [
      'Toque no campo de texto.',
      'Feche e abra o app.',
      'Reinicie se não voltar.',
    ],
    [
      'Toque no campo de texto.',
      'Feche e abra o app.',
      'Reinicie se não voltar.',
    ],
    'Campo de texto com teclado aberto.',
    'Peça ajuda se nenhum teclado aparecer.',
  ),
  _help(
    'small-text',
    'Letra muito pequena',
    'Acessibilidade',
    ['Abra Configurações.', 'Procure Tamanho da fonte.', 'Aumente a letra.'],
    ['Abra Ajustes.', 'Toque em Tela e Brilho.', 'Aumente o tamanho do texto.'],
    'Texto maior e mais fácil de ler.',
    'Peça ajuda se os botões ficarem fora da tela.',
  ),
  _help(
    'no-signal',
    'Sem sinal da operadora',
    'Sinal',
    ['Confira modo avião.', 'Vá para local aberto.', 'Reinicie o celular.'],
    ['Confira modo avião.', 'Vá para local aberto.', 'Reinicie o iPhone.'],
    'Barras de sinal no topo da tela.',
    'Fale com a operadora se ficar sem sinal por muito tempo.',
  ),
];

Training trainingByName(String name) => trainings.firstWhere(
  (item) => item.name == name,
  orElse: () => trainings.first,
);
DictionaryTerm termByKey(String key) => dictionaryTerms.firstWhere(
  (item) => item.key == key,
  orElse: () => dictionaryTerms.first,
);
DeviceHelp helpByKey(String key) => deviceHelpItems.firstWhere(
  (item) => item.key == key,
  orElse: () => deviceHelpItems.first,
);

const callSteps = <String>[
  'Abra o aplicativo de telefone (ícone de telefone).',
  'Toque no teclado numérico.',
  'Digite o número desejado.',
  'Toque no botão verde de ligar.',
  'Espere a pessoa atender.',
  'Para encerrar, toque no botão vermelho.',
];

FaqItem _faq(String category, String question, String answer) =>
    FaqItem(category: category, question: question, answer: answer);

final faqItems = <FaqItem>[
  _faq(
    'Golpes e segurança',
    'O que é um link?',
    'Link é um caminho para outra página. Se veio de desconhecido, não toque. Procure o site ou app oficial.',
  ),
  _faq(
    'Golpes e segurança',
    'Como sei se uma mensagem é golpe?',
    'Desconfie de pressa, prêmio, ameaça, pedido de senha, código ou dinheiro. Na dúvida, pare e peça ajuda.',
  ),
  _faq(
    'Golpes e segurança',
    'O que fazer se cliquei em um link suspeito?',
    'Não informe dados. Feche a página, troque senhas importantes e procure ajuda de confiança.',
  ),
  _faq(
    'Internet e Wi-Fi',
    'Posso usar Wi-Fi público para acessar o banco?',
    'Evite. Prefira dados móveis ou Wi-Fi de casa para acessar banco.',
  ),
  _faq(
    'Celular sem funcionar',
    'O que fazer se o celular parou de funcionar?',
    'Tente reiniciar segurando o botão de ligar. Se não resolver, procure ajuda.',
  ),
  _faq(
    'WhatsApp',
    'Como bloquear um número que está me perturbando?',
    'Abra a conversa, toque no nome ou nos três pontos e escolha Bloquear.',
  ),
  _faq(
    'Golpes e segurança',
    'O que fazer se recebi um link estranho?',
    'Não abra. Apague a mensagem ou mostre para alguém de confiança.',
  ),
  _faq(
    'Banco digital',
    'O banco pode pedir minha senha pelo WhatsApp?',
    'Não. Banco nenhum pede senha por mensagem. Use apenas o app ou telefone oficial.',
  ),
  _faq(
    'Senhas e códigos',
    'O que fazer se passei um código por engano?',
    'Avise a pessoa de confiança, troque senhas e procure o suporte oficial da conta.',
  ),
  _faq(
    'Senhas e códigos',
    'Como criar uma senha mais segura?',
    'Use frase ou combinação que só você sabe. Evite data de nascimento e nomes óbvios.',
  ),
  _faq(
    'Senhas e códigos',
    'Posso usar a mesma senha em tudo?',
    'Não é seguro. Se uma conta vazar, outras podem ser invadidas.',
  ),
  _faq(
    'Senhas e códigos',
    'O que é autenticação em duas etapas?',
    'É uma proteção extra. Além da senha, a conta pede código ou confirmação.',
  ),
  _faq(
    'Pix e pagamentos',
    'Como saber se um boleto é falso?',
    'Confira nome do beneficiário, valor, vencimento e canal onde recebeu o boleto.',
  ),
  _faq(
    'WhatsApp',
    'O que fazer se meu WhatsApp foi clonado?',
    'Tente recuperar pelo app, avise contatos e ative verificação em duas etapas.',
  ),
  _faq(
    'Celular sem funcionar',
    'O que fazer se o celular travou?',
    'Feche o app travado ou reinicie o celular. Não aperte tudo com pressa.',
  ),
  _faq(
    'Celular sem funcionar',
    'Como aumentar o volume?',
    'Use os botões laterais e confira se o celular não está no silencioso.',
  ),
  _faq(
    'Internet e Wi-Fi',
    'Como saber se estou no Wi-Fi?',
    'Procure o desenho de Wi-Fi no topo da tela ou veja nas configurações.',
  ),
  _faq(
    'Internet e Wi-Fi',
    'O que são dados móveis?',
    'É a internet do chip da operadora. Funciona fora de casa se houver sinal.',
  ),
  _faq(
    'Aplicativos',
    'Como fechar um aplicativo travado?',
    'Abra apps recentes e deslize o app para fechar. Depois abra de novo.',
  ),
  _faq(
    'Aplicativos',
    'Como atualizar um aplicativo?',
    'Abra Play Store ou App Store, procure o app e toque em Atualizar.',
  ),
  _faq(
    'Golpes e segurança',
    'Devo baixar app enviado por mensagem?',
    'Não. Baixe aplicativos apenas pela loja oficial do celular.',
  ),
  _faq(
    'Aplicativos',
    'Como conferir se um aplicativo é verdadeiro?',
    'Veja se está na loja oficial, confira nome, desenvolvedor e avaliações.',
  ),
  _faq(
    'Pix e pagamentos',
    'O que é Pix?',
    'Pix é transferência rápida pelo banco. Confira nome e valor antes de confirmar.',
  ),
  _faq(
    'Pix e pagamentos',
    'Posso cancelar um Pix?',
    'Na maioria das vezes, não. Por isso confira tudo antes de confirmar.',
  ),
  _faq(
    'Pix e pagamentos',
    'Como conferir o nome antes de transferir?',
    'Antes de confirmar, leia o nome do recebedor, banco e valor na tela.',
  ),
  _faq(
    'Pix e pagamentos',
    'O que é comprovante?',
    'É o registro da operação. Mas imagem pode ser falsa; confira no extrato.',
  ),
  _faq(
    'Banco digital',
    'O que fazer se apareceu uma cobrança desconhecida?',
    'Anote valor e data. Fale com o banco pelo app ou telefone oficial.',
  ),
  _faq(
    'WhatsApp',
    'Um familiar pediu dinheiro por número novo. O que faço?',
    'Ligue para o número antigo ou confirme com outro familiar antes de transferir.',
  ),
  _faq(
    'Internet e Wi-Fi',
    'Wi-Fi público é sempre seguro?',
    'Não. Use com cuidado e evite banco, compras e senhas em rede pública.',
  ),
  _faq(
    'Aplicativos',
    'O que fazer se um app pediu muitas permissões?',
    'Negue se não fizer sentido. Um app simples não precisa de tudo.',
  ),
  _faq(
    'Banco digital',
    'O que é saldo?',
    'É o dinheiro disponível na conta naquele momento. Confira sempre no app oficial.',
  ),
  _faq(
    'Banco digital',
    'O que é extrato?',
    'É a lista de entradas e saídas da conta. Ajuda a conferir cobranças.',
  ),
  _faq(
    'Golpes e segurança',
    'Na dúvida, devo responder a mensagem?',
    'Não precisa responder. Feche, salve prova se necessário e peça ajuda.',
  ),
  _faq(
    'Senhas e códigos',
    'Alguém pediu foto do meu documento. Posso enviar?',
    'Só envie em app oficial e confiável. Nunca mande para desconhecidos no WhatsApp.',
  ),
  _faq(
    'Celular sem funcionar',
    'O teclado sumiu. O que faço?',
    'Toque no campo de texto. Se não voltar, feche o app e abra de novo.',
  ),
  _faq(
    'Celular sem funcionar',
    'A letra está pequena. Como melhorar?',
    'Aumente o tamanho da fonte nas configurações ou use o botão de texto do Lia Simplis.',
  ),
];

QuizQuestion _quiz(
  String id,
  String category,
  String level,
  String question,
  String a,
  String b,
  String c,
  String correct,
  String explanation,
) => QuizQuestion(
  id: id,
  category: category,
  level: level,
  question: question,
  alternatives: [
    QuizAlternative(id: 'a', text: a),
    QuizAlternative(id: 'b', text: b),
    QuizAlternative(id: 'c', text: c),
  ],
  correctAnswerId: correct,
  explanation: explanation,
);

final quizQuestions = <QuizQuestion>[
  _quiz(
    'q1',
    'Banco digital',
    'Fácil',
    'Um banco pediu sua senha pelo WhatsApp. O que você faz?',
    'Envia a senha',
    'Não envia e abre o app oficial',
    'Responde perguntando por quê',
    'b',
    'Boa escolha. Banco nenhum pede senha por mensagem.',
  ),
  _quiz(
    'q2',
    'Senhas e códigos',
    'Fácil',
    'Você recebeu um código SMS e alguém pediu esse código. O que fazer?',
    'Guardar o código e não enviar',
    'Enviar rápido',
    'Postar no grupo',
    'a',
    'Boa escolha. Nunca compartilhe códigos de segurança.',
  ),
  _quiz(
    'q3',
    'Pix e pagamentos',
    'Fácil',
    'Antes de fazer Pix, o que você deve conferir?',
    'Nome, valor e banco do recebedor',
    'Só a foto da pessoa',
    'Nada, Pix é sempre seguro',
    'a',
    'Isso. Conferir os dados evita envio para pessoa errada.',
  ),
  _quiz(
    'q4',
    'Golpes e segurança',
    'Fácil',
    'Um link promete prêmio em dinheiro. O que é mais seguro?',
    'Abrir correndo',
    'Não abrir e pedir ajuda',
    'Enviar para todos',
    'b',
    'Boa escolha. Prêmios por link costumam ser golpe.',
  ),
  _quiz(
    'q5',
    'Celular',
    'Fácil',
    'O celular ficou sem som. Qual o primeiro passo?',
    'Aumentar volume e conferir silencioso',
    'Apagar aplicativos',
    'Enviar senha ao suporte',
    'a',
    'Isso. Comece pelo ajuste simples e seguro.',
  ),
  _quiz(
    'q6',
    'Internet e Wi-Fi',
    'Médio',
    'Wi-Fi público é sempre seguro para acessar banco?',
    'Sim',
    'Não',
    'Só se tiver nome bonito',
    'b',
    'Correto. Prefira dados móveis ou Wi-Fi de confiança.',
  ),
  _quiz(
    'q7',
    'Aplicativos',
    'Fácil',
    'O que fazer antes de baixar um aplicativo?',
    'Conferir se está na loja oficial',
    'Instalar link recebido',
    'Desligar o celular',
    'a',
    'Boa. Loja oficial reduz risco de app falso.',
  ),
  _quiz(
    'q8',
    'WhatsApp',
    'Fácil',
    'Um número novo diz ser seu familiar e pede dinheiro. O que fazer?',
    'Transferir rápido',
    'Confirmar por ligação ou outro familiar',
    'Mandar código SMS',
    'b',
    'Isso. Confirme identidade antes de qualquer pagamento.',
  ),
  _quiz(
    'q9',
    'Pix e pagamentos',
    'Médio',
    'Um comprovante chegou por imagem. O que confirma pagamento?',
    'A imagem bonita',
    'O valor no extrato do banco',
    'A pressa da pessoa',
    'b',
    'Correto. Confira sempre no extrato.',
  ),
  _quiz(
    'q10',
    'Golpes e segurança',
    'Fácil',
    'Mensagem com ameaça e pressa costuma indicar o quê?',
    'Possível golpe',
    'Mensagem sempre oficial',
    'Promoção garantida',
    'a',
    'Isso. Golpes usam medo e urgência.',
  ),
  _quiz(
    'q11',
    'Senhas e códigos',
    'Médio',
    'Usar a mesma senha em tudo é seguro?',
    'Não',
    'Sim',
    'Só no domingo',
    'a',
    'Correto. Senhas diferentes protegem melhor.',
  ),
  _quiz(
    'q12',
    'Banco digital',
    'Fácil',
    'Uma cobrança desconhecida apareceu. O que fazer?',
    'Anotar e falar com banco oficial',
    'Passar senha a quem ligou',
    'Ignorar sempre',
    'a',
    'Boa. Use canal oficial e tenha valor/data em mãos.',
  ),
  _quiz(
    'q13',
    'Aplicativos',
    'Fácil',
    'Atualização de banco deve ser feita onde?',
    'Na loja oficial',
    'Em qualquer link',
    'Por arquivo enviado no WhatsApp',
    'a',
    'Correto. Use Play Store ou App Store.',
  ),
  _quiz(
    'q14',
    'Segurança',
    'Médio',
    'Um app de lanterna pediu acesso a contatos e banco. O que fazer?',
    'Aceitar tudo',
    'Desconfiar e negar permissões',
    'Enviar CPF',
    'b',
    'Isso. Permissão deve fazer sentido.',
  ),
  _quiz(
    'q15',
    'Internet e Wi-Fi',
    'Fácil',
    'Dados móveis são...',
    'Internet do chip da operadora',
    'Senha do banco',
    'Foto do documento',
    'a',
    'Correto. Dados móveis usam o chip.',
  ),
  _quiz(
    'q16',
    'Celular',
    'Fácil',
    'Se a tela está muito escura, você pode...',
    'Aumentar o brilho',
    'Mandar senha para suporte',
    'Formatar o celular',
    'a',
    'Boa. Brilho é ajuste simples e seguro.',
  ),
  _quiz(
    'q17',
    'WhatsApp',
    'Médio',
    'Contato insistente envia links perigosos. O que fazer?',
    'Bloquear e denunciar',
    'Clicar para testar',
    'Enviar para amigos',
    'a',
    'Correto. Bloquear reduz risco.',
  ),
  _quiz(
    'q18',
    'Pix e pagamentos',
    'Médio',
    'No boleto, o beneficiário está diferente. O que fazer?',
    'Não pagar e confirmar com a empresa',
    'Pagar assim mesmo',
    'Mandar foto do documento',
    'a',
    'Boa escolha. Beneficiário diferente é sinal de alerta.',
  ),
  _quiz(
    'q19',
    'Segurança',
    'Fácil',
    'Na dúvida sobre uma mensagem, o mais seguro é...',
    'Parar e pedir ajuda',
    'Responder com seus dados',
    'Clicar para ver',
    'a',
    'Isso. Pedir ajuda é uma atitude segura.',
  ),
  _quiz(
    'q20',
    'Celular',
    'Fácil',
    'Modo avião ligado pode causar...',
    'Sem ligação e sem internet móvel',
    'Mais senha',
    'Pix automático',
    'a',
    'Correto. Desative se precisar de sinal.',
  ),
  _quiz(
    'q21',
    'Banco digital',
    'Médio',
    'Uma pessoa quer ver sua tela enquanto você abre o banco. O que fazer?',
    'Não compartilhar a tela',
    'Mostrar saldo e senha',
    'Fazer Pix de teste',
    'a',
    'Boa. Nunca mostre tela de banco para desconhecidos.',
  ),
  _quiz(
    'q22',
    'Aplicativos',
    'Fácil',
    'App falso pode parecer...',
    'Muito parecido com o verdadeiro',
    'Sempre vermelho',
    'Sem nome',
    'a',
    'Correto. Confira loja, nome e desenvolvedor.',
  ),
  _quiz(
    'q23',
    'Segurança',
    'Médio',
    'Pedir segredo junto com dinheiro urgente é...',
    'Sinal de alerta',
    'Prova de confiança',
    'Obrigatório',
    'a',
    'Isso. Golpes tentam isolar a pessoa.',
  ),
  _quiz(
    'q24',
    'Internet e Wi-Fi',
    'Fácil',
    'Para abrir banco fora de casa, é melhor...',
    'Usar dados móveis ou rede confiável',
    'Usar qualquer Wi-Fi grátis',
    'Pedir senha a estranho',
    'a',
    'Correto. Evite redes desconhecidas.',
  ),
  _quiz(
    'q25',
    'Senhas e códigos',
    'Fácil',
    'Autenticação em duas etapas serve para...',
    'Proteger melhor a conta',
    'Enviar dinheiro',
    'Aumentar volume',
    'a',
    'Boa. É uma camada extra de segurança.',
  ),
];
